#include "ui/localization.hpp"
#include <array>
namespace pastit {
UiLanguage resolve_language(UiLanguage requested,std::string_view locale){if(requested!=UiLanguage::System)return requested;return locale.starts_with("zh")?UiLanguage::SimplifiedChinese:UiLanguage::English;}
std::string tr(UiLanguage language,UiTextKey key){
 const bool zh=language==UiLanguage::SimplifiedChinese;
 const auto pick=[&](const char* en,const char* cn){return std::string{zh?cn:en};};
 switch(key){
 case UiTextKey::SmartActions:return pick("Smart Actions","智能动作");case UiTextKey::RecentPaths:return pick("Recent Paths","最近路径");case UiTextKey::Settings:return pick("Settings","设置");case UiTextKey::General:return pick("General","常规");case UiTextKey::Copy:return pick("Copy","复制");case UiTextKey::Open:return pick("Open","打开");case UiTextKey::Move:return pick("Move","移动");case UiTextKey::Save:return pick("Save","保存");case UiTextKey::Cancel:return pick("Cancel","取消");case UiTextKey::PromptTemplates:return pick("Prompt Templates","提示词模板");case UiTextKey::GeneralLlm:return pick("General LLM","通用 LLM");case UiTextKey::Djev:return pick("Jev-compatible API","Jev 兼容 API");
 case UiTextKey::Target:return pick("Target","目标");case UiTextKey::NoClipboard:return pick("No clipboard item captured yet.","尚未捕获剪贴板内容。");case UiTextKey::WaitingDjev:return pick("Waiting for local Djev…","等待本地 Djev…");case UiTextKey::NoRankedActions:return pick("No ranked actions","没有可用动作");
 case UiTextKey::Type:return pick("Type","类型");case UiTextKey::Name:return pick("Name","名称");case UiTextKey::Path:return pick("Path","路径");case UiTextKey::Source:return pick("Source","来源");case UiTextKey::Actions:return pick("Actions","操作");case UiTextKey::Folder:return pick("Folder","文件夹");case UiTextKey::File:return pick("File","文件");case UiTextKey::CopyHere:return pick("Copy here","复制到这里");case UiTextKey::MoveHere:return pick("Move here","移动到这里");
 case UiTextKey::CopyPath:return pick("Copy path","复制路径");case UiTextKey::OpenResult:return pick("Open result","打开结果");case UiTextKey::OpenFolder:return pick("Open folder","打开文件夹");case UiTextKey::ImagePreview:return pick("Image Preview","图片预览");case UiTextKey::CopyImage:return pick("Copy Image","复制图片");case UiTextKey::CopyTemporaryPath:return pick("Copy temporary path","复制临时路径");case UiTextKey::OpenTemporaryFile:return pick("Open Temporary File","打开临时文件");
 case UiTextKey::AiResult:return pick("AI Result","AI 结果");case UiTextKey::Generating:return pick("Generating…","生成中…");case UiTextKey::CopyResult:return pick("Copy Result","复制结果");case UiTextKey::ReplaceClipboard:return pick("Replace Clipboard","替换剪贴板");case UiTextKey::Retry:return pick("Retry","重试");case UiTextKey::Language:return pick("Language","语言");case UiTextKey::Opacity:return pick("Opacity","透明度");
 case UiTextKey::DefaultImageDirectory:return pick("Default image directory","默认图片目录");case UiTextKey::DefaultTextDirectory:return pick("Default text directory","默认文本目录");case UiTextKey::DjevEndpoint:return pick("Jev API endpoint","Jev API 地址");case UiTextKey::DjevModel:return pick("Jev API model","Jev API 模型");case UiTextKey::DjevApiKey:return pick("Jev API key","Jev API 密钥");case UiTextKey::LlmEndpoint:return pick("LLM endpoint","LLM 地址");case UiTextKey::LlmModel:return pick("LLM model","LLM 模型");case UiTextKey::LlmApiKey:return pick("LLM API key","LLM API 密钥");
 case UiTextKey::TestDjev:return pick("Test Jev API","测试 Jev API");case UiTextKey::TestGeneralLlm:return pick("Test General LLM","测试通用 LLM");case UiTextKey::TemplateName:return pick("Template name","模板名称");case UiTextKey::SystemPrompt:return pick("System prompt","系统提示词");case UiTextKey::Enabled:return pick("Enabled","启用");case UiTextKey::Temperature:return pick("Temperature","温度");case UiTextKey::Duplicate:return pick("Duplicate","复制模板");case UiTextKey::Delete:return pick("Delete","删除");case UiTextKey::ConfirmDelete:return pick("Confirm delete","确认删除");case UiTextKey::Keep:return pick("Keep","保留");case UiTextKey::NewTemplate:return pick("New template","新建模板");case UiTextKey::RestoreDefaults:return pick("Restore defaults","恢复默认");case UiTextKey::ResetGeneral:return pick("Reset General","重置常规");case UiTextKey::ResetPaths:return pick("Reset Paths","重置路径");case UiTextKey::ResetProviders:return pick("Reset Providers","重置服务商");case UiTextKey::DeleteQuestion:return pick("Delete this template?","删除这个模板？");
 case UiTextKey::KeyboardHint:return pick("↑/↓ choose  •  Enter execute  •  Esc close","↑/↓ 选择  •  Enter 执行  •  Esc 关闭");case UiTextKey::Zoom:return pick("Zoom","缩放");case UiTextKey::DjevTestSucceeded:return pick("Jev API connection succeeded","Jev API 连接成功");case UiTextKey::DjevTestFailed:return pick("Jev API test failed: ","Jev API 测试失败：");case UiTextKey::GeneralLlmTestSucceeded:return pick("General LLM connection succeeded","通用 LLM 连接成功");case UiTextKey::GeneralLlmTestFailed:return pick("General LLM test failed: ","通用 LLM 测试失败：");case UiTextKey::Saved:return pick("Saved","已保存");case UiTextKey::OpenedTemporaryImage:return pick("Opened temporary image: ","已打开临时图片：");case UiTextKey::KeepLatest10:return pick("Keep latest 10","保留最近 10 条");case UiTextKey::DeleteAllHistory:return pick("Delete all history","删除全部历史");case UiTextKey::RefreshModels:return pick("Refresh models","刷新模型");case UiTextKey::ModelList:return pick("Available models","可用模型");case UiTextKey::ModelListFailed:return pick("Model list unavailable: ","模型列表不可用：");case UiTextKey::HistoryPruned:return pick("History pruned to latest 10","历史已保留最近 10 条");case UiTextKey::HistoryDeleted:return pick("All history deleted","历史已全部删除");
 case UiTextKey::ClipboardHistory:return pick("Clipboard History","剪贴板历史");case UiTextKey::Preview:return pick("Preview","预览");case UiTextKey::Size:return pick("Size","大小");case UiTextKey::Captured:return pick("Captured","捕获时间");case UiTextKey::Details:return pick("Details","详情");case UiTextKey::View:return pick("View","查看");case UiTextKey::Edit:return pick("Edit","编辑");case UiTextKey::Close:return pick("Close","关闭");case UiTextKey::MimeTypes:return pick("MIME Types","MIME 类型");case UiTextKey::MissingData:return pick("Missing data","数据缺失");case UiTextKey::PromptActions:return pick("Prompt Actions","提示词动作");case UiTextKey::ConfigureGeneralLlm:return pick("Configure General LLM","配置通用 LLM");case UiTextKey::BuiltIn:return pick("Built-in","内置");case UiTextKey::Custom:return pick("Custom","自定义");case UiTextKey::Browse:return pick("Browse","浏览");case UiTextKey::Destination:return pick("Destination","目标目录");case UiTextKey::Filename:return pick("Filename","文件名");case UiTextKey::OutputPath:return pick("Output path","输出路径");case UiTextKey::Confirm:return pick("Confirm","确认");case UiTextKey::InvalidPath:return pick("Invalid destination path","目标路径无效");case UiTextKey::InvalidFilename:return pick("Invalid filename","文件名无效");case UiTextKey::SourceParent:return pick("Source parent","来源父目录");case UiTextKey::FocusedDirectory:return pick("Focused directory","当前应用目录");case UiTextKey::ManualDestination:return pick("Manual destination","手动目标目录");case UiTextKey::DeleteTemplateText:return pick("Delete this prompt template?","删除此提示词模板？");case UiTextKey::DuplicateTemplateText:return pick("Duplicate prompt template","复制提示词模板");case UiTextKey::UseAsDestination:return pick("Use as destination","设为目标目录");case UiTextKey::OpenParent:return pick("Open parent","打开父目录");case UiTextKey::Use:return pick("Use","使用");case UiTextKey::Seen:return pick("Seen","最近访问");case UiTextKey::Parent:return pick("Parent","父目录");case UiTextKey::Reference:return pick("Reference","引用");case UiTextKey::CopyHereAction:return pick("Copy-here action","复制到此动作");case UiTextKey::MoveHereAction:return pick("Move-here action","移动到此动作");case UiTextKey::ConfirmFileOperation:return pick("Confirm File Operation","确认文件操作");
 case UiTextKey::GraphData:return pick("Graph data","绘制图表");case UiTextKey::GraphPreview:return pick("Graph preview","图表预览");case UiTextKey::ChartType:return pick("Chart type","图表类型");case UiTextKey::HeaderRow:return pick("Header row","首行为表头");case UiTextKey::ConvertDates:return pick("Convert dates","转换日期");case UiTextKey::SavePngAs:return pick("Save PNG as","PNG 保存路径");case UiTextKey::CopyGraphImage:return pick("Copy image","复制图片");case UiTextKey::SaveGraphImage:return pick("Save image","保存图片");case UiTextKey::CustomPrompt:return pick("Custom prompt","自定义提示词");case UiTextKey::PromptInstructions:return pick("Instructions for the copied text:","对剪贴板文本的指令：");case UiTextKey::Generate:return pick("Generate","生成");case UiTextKey::AnnotateImage:return pick("Annotate image","标注图片");
 case UiTextKey::UsageInsights:return pick("Usage insights","使用习惯");case UiTextKey::UsageInsightsHelp:return pick("Your most frequent choices per content type. They nudge the ranking and are sent to Jev as habits; older choices fade after about two weeks.","按内容类型统计的常用操作。它们会提升排序，并作为习惯发送给 Jev；旧的选择约两周后衰减。");case UiTextKey::UsageInsightsEmpty:return pick("No choices recorded yet.","尚无记录。");case UiTextKey::ResetUsage:return pick("Reset usage history","重置使用习惯");case UiTextKey::UsageReset:return pick("Usage history cleared.","已清除使用习惯。");case UiTextKey::FastActions:return pick("Fast actions","快捷操作");
 case UiTextKey::StatusIdle:return pick("Ready","就绪");case UiTextKey::StatusRanking:return pick("Ranking…","排序中…");case UiTextKey::StatusRanked:return pick("Ranked by Jev","由 Jev 排序");case UiTextKey::StatusFallback:return pick("Local ranking","本地排序");case UiTextKey::ClickToCopy:return pick("Click to copy","点击复制");case UiTextKey::Theme:return pick("Theme","主题");case UiTextKey::ThemeDark:return pick("Dark","深色");case UiTextKey::ThemeLight:return pick("Light","浅色");
 case UiTextKey::ConfirmOverwrite:return pick("Confirm overwrite","确认覆盖");case UiTextKey::FastAnnotation:return pick("Fast annotation","快速标注");case UiTextKey::Comment:return pick("Comment","批注");case UiTextKey::Undo:return pick("Undo","撤销");case UiTextKey::Clear:return pick("Clear","清除");case UiTextKey::SaveAnnotatedSvg:return pick("Save annotated SVG","保存标注 SVG");case UiTextKey::CopyTemporaryImagePath:return pick("Copy temporary image path","复制临时图片路径");case UiTextKey::OpenPngExternally:return pick("Open PNG externally","用外部程序打开 PNG");case UiTextKey::Pause:return pick("Pause","暂停");case UiTextKey::Resume:return pick("Resume","继续");case UiTextKey::ClipboardHistoryDetail:return pick("Clipboard History Detail","剪贴板历史详情");case UiTextKey::RecentPathDetail:return pick("Recent Path Detail","最近路径详情");case UiTextKey::MermaidRendererHelp:return pick("Mermaid uses mmdc for an in-window image when available; offline HTML is the fallback.","Mermaid 优先使用 mmdc 生成窗口内图片；否则回退为离线 HTML。");case UiTextKey::MermaidHomepage:return pick("Mermaid homepage","Mermaid 主页");case UiTextKey::MermaidCliPath:return pick("Mermaid CLI path (optional)","Mermaid CLI 路径（可选）");case UiTextKey::MermaidCliArguments:return pick("Mermaid CLI arguments","Mermaid CLI 参数");case UiTextKey::QrHelp:return pick("QR codes use the native Project Nayuki library.","二维码使用内置的 Project Nayuki 库生成。");case UiTextKey::QrHomepage:return pick("QR library homepage","二维码库主页");case UiTextKey::QrErrorCorrection:return pick("QR error correction (L/M/Q/H)","二维码纠错级别 (L/M/Q/H)");case UiTextKey::QrMargin:return pick("QR margin","二维码边距");case UiTextKey::QrScale:return pick("QR scale","二维码缩放");case UiTextKey::DownloadResumeDirectory:return pick("Download resume directory","下载续传目录");case UiTextKey::KeepPartFiles:return pick("Keep .part files after cancel","取消后保留 .part 文件");case UiTextKey::TerminalCommand:return pick("Terminal command","终端命令");case UiTextKey::TerminalProfile:return pick("Terminal profile (stored; launcher support pending)","终端配置（已保存，启动器支持待定）");case UiTextKey::ShowSha256:return pick("Show SHA-256 hash action","显示 SHA-256 哈希操作");case UiTextKey::ShowSha512:return pick("Show SHA-512 hash action","显示 SHA-512 哈希操作");case UiTextKey::DateSpacingEnabled:return pick("Date spacing enabled","已按日期间隔");case UiTextKey::Points:return pick("points","个数据点");
 }
 return {};
}
namespace { UiLanguage active_language = UiLanguage::English; }
void set_active_language(UiLanguage language){active_language=language;}
std::string tr(UiTextKey key){return tr(active_language,key);}
}
