#!/usr/bin/env python3
"""Generate src/ui/localization_ja_ko.cpp from src/ui/i18n/ja.json and ko.json.

Each JSON file maps UiTextKey names to the text as C string-literal contents
(escapes such as \\n or \\xC2\\xB7 kept as written). Keys missing from a file
fall back to English at run time; unknown keys are an error.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
header = (ROOT / "src/ui/localization.hpp").read_text(encoding="utf-8")
enum = re.search(r"enum class UiTextKey\s*\{(.*?)\};", header, re.S).group(1)
keys = [key.strip() for key in enum.replace("\n", " ").split(",") if key.strip()]


def table(language: str, function: str) -> str:
    data = json.loads((ROOT / f"src/ui/i18n/{language}.json").read_text(encoding="utf-8"))
    unknown = sorted(set(data) - set(keys))
    if unknown:
        sys.exit(f"{language}.json has unknown keys: {unknown}")
    lines = [f"const char* {function}(UiTextKey key) {{", "    switch (key) {"]
    for key in keys:
        if key in data:
            text = data[key].replace("\r", "")
            if '"' in text.replace('\\"', ""):
                sys.exit(f"{language}.json {key}: unescaped quote")
            lines.append(f'        case UiTextKey::{key}: return "{text}";')
    lines += ["        default: return nullptr;", "    }", "}"]
    missing = [key for key in keys if key not in data]
    print(f"{language}: {len(data)} of {len(keys)} keys" + (f"; missing {missing[:8]}" if missing else ""), file=sys.stderr)
    if missing and "--check" in sys.argv:
        sys.exit(f"{language}.json is missing {len(missing)} keys")
    return "\n".join(lines)


# --check: fail on missing keys and leave the generated file alone.
body = "\n\n".join([table("ja", "tr_japanese"), table("ko", "tr_korean")])
if "--check" in sys.argv:
    sys.exit(0)
(ROOT / "src/ui/localization_ja_ko.cpp").write_text(
    "// Generated by scripts/gen_cjk_localization.py from src/ui/i18n/*.json; do not edit.\n"
    '#include "ui/localization.hpp"\n\nnamespace pasteit {\n\n' + body + "\n\n}  // namespace pasteit\n",
    encoding="utf-8")
